/**
 * 과제 4용 Mock Data.
 * 실제 API 대신 도시 코드(cityId)로 찾아 쓰는 임시 데이터다.
 * WeatherDetailView 가 route.params.cityId 로 여기서 한 건을 골라낸다.
 */
export const MOCK_CITIES = [
  {
    id: 'city_01',
    name: '서울',
    region: '서울',
    temp: 28,
    humidity: 45,
    status: '맑음',
    wind: 2.4,
    pressure: 1012,
    visibility: 12,
    dust: '보통',
    sunrise: '05:32',
    sunset: '19:48',
  },
  {
    id: 'city_02',
    name: '수원',
    region: '경기',
    temp: 24,
    humidity: 88,
    status: '비',
    wind: 3.1,
    pressure: 1005,
    visibility: 4,
    dust: '좋음',
    sunrise: '05:34',
    sunset: '19:47',
  },
  {
    id: 'city_03',
    name: '부산',
    region: '경남',
    temp: 26,
    humidity: 72,
    status: '구름',
    wind: 4.6,
    pressure: 1009,
    visibility: 9,
    dust: '보통',
    sunrise: '05:21',
    sunset: '19:36',
  },
  {
    id: 'city_04',
    name: '강릉',
    region: '강원',
    temp: 21,
    humidity: 92,
    status: '안개',
    wind: 1.2,
    pressure: 1011,
    visibility: 2,
    dust: '좋음',
    sunrise: '05:24',
    sunset: '19:41',
  },
  {
    id: 'city_05',
    name: '대구',
    region: '경북',
    temp: 31,
    humidity: 33,
    status: '맑음',
    wind: 1.8,
    pressure: 1008,
    visibility: 14,
    dust: '나쁨',
    sunrise: '05:26',
    sunset: '19:39',
  },
  {
    id: 'city_06',
    name: '제주',
    region: '제주',
    temp: 29,
    humidity: 64,
    status: '소나기',
    wind: 5.2,
    pressure: 1006,
    visibility: 6,
    dust: '좋음',
    sunrise: '05:38',
    sunset: '19:44',
  },
]

/** 도시 코드로 한 건 찾기. 없으면 null */
export const findMockCity = (cityId) => MOCK_CITIES.find((c) => c.id === cityId) ?? null
